spring:
  datasource:
#    url: jdbc:mysql://10.0.30.59:3306/airbnb
    url: datasource_url
    username: datasource_username
    password: datasource_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validation
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
